### ISSUE TITLE
Messaging tab - comments on extremely old threads don't load correctly

### ISSUE THREAD

**Issue by lisa-wolfgang** [ScratchAddons/ScratchAddons#2466]
**Describe the bug**

When a comment referenced in a user's messages is from a long time ago, the comment fails to appear in the Messaging tab.

**To Reproduce**

1. Using an alt account or other willing test subject, navigate to an extremely old comment thread (a year should suffice, or perhaps less time on active/popular projects, studios, or profiles) and reply to one of the messages sent by your main account
2. Go to Scratch Addon's Messaging tab and confirm that the message doesn't show (an empty header should be there instead)
3. Navigate to your main account's Messages page (on scratch.mit.edu) and confirm that the message exists
4. Open the provided link to the comment in the Messages page and confirm that the message is showing up

**Expected behavior**

If it's a timeout issue, it would probably take too long to actually load the message, especially for really ancient threads, so perhaps a notice like [message failed to load] or [message not found] should appear.

**Screenshots**

This is what it looked like when the messages were unread:
![image](https://user-images.githubusercontent.com/43426138/117685988-0b628880-b17c-11eb-95f8-78a1b4e3f0dc.png)

After messages were marked as read and the "Load more messages" button was used: (note the "3" count, then count how many comments there actually are)
![image](https://user-images.githubusercontent.com/43426138/117679662-16b2b580-b176-11eb-996d-caf1ac8260f5.png)
The comment in question (https://scratch.mit.edu/projects/275999360/#comments-206329971) is about a year old, and there has been a significant amount of comments posted since then.

**Device (please complete the following information):**

- OS: Windows 10
- Browser: Chromium 90.0.4430.93
- Version: 1.14.2

**Comment by Shluffy** [comment]
> The comment in question (https://scratch.mit.edu/projects/275999360/#comments-206329971) is both very old and on a long thread, so I'm not sure which of these is causing the issue.

This is probably on how old it is, not how long it is as SA has had no problems pulling long threads for me.

**Comment by lisa-wolfgang** [comment]
> This is probably on how old it is, not how long it is as SA has had no problems pulling long threads for me.
Thank you, that's what I suspected, but I didn't know for sure.

**Comment by lisa-wolfgang** [comment]
> Could not reproduce.
> It pulled all the comments so far as I can tell, so unless I missed one it works fine.
> Browser: Google Chrome OS Version 91.0.4472.33 (Official Build) beta (64-bit)
> 
> How old is 'extremely old'. I tested on a 96 day old thread and it loaded, but should I test on older.

You should probably test on something older, preferably on something that's now buried under many, many more comments.

**Comment by mxmou** [comment]
I think Scratch's old comment API has a maximum number of pages of comments it can load. For projects and studios this could be fixed by moving to the current API, and for profile pages a good solution might be to show just the comment as returned by the messages API (not the whole thread).

**Comment by TheColaber** [comment]
I think the new json API might solve this? Because it should have something like /:projectid/:commentid/replies and /:profileuser/:commentid/replies and /:studioid/:commentid/replies

**Comment by mxmou** [comment]
@Shluffy It would still show the whole thread except if it can't load it.

@TheColaber It would, but I don't think it's available for profile comments yet.

**Comment by WorldLanguages** [comment]
This can be fixed for studios and profiles with #2046

**Comment by lisa-wolfgang** [comment]
Fixed by #2501.

![image](https://user-images.githubusercontent.com/43426138/118401064-d34ec000-b629-11eb-8927-e386031c0975.png)

**Comment by mxmou** [comment]
It's probably still a problem on profile pages.

**Comment by RedGuy12** [comment]
Yeah, still an issue with profiles. I added the pending label since it's not possible to fix it without a new API.

**Comment by mxmou** [comment]
@RedGuy12 I think it should just display the fragment given by the API as a temporary solution.

**Comment by apple502j** [comment]
This is a wontfix, I guess. Not too common.

**Comment by mxmou** [comment]
@apple502j Maybe add an error message when a comment fails to load instead?

**Comment by WorldLanguages** [comment]
Eh... 
> I think it should just display the fragment given by the API as a temporary solution.

Still valid
