### ISSUE TITLE
Removing support for userscript.if

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#5272]
It's convenient to declare whether a userscript should run depending on the value of a setting or whether a different addon is enabled.
However, this pattern means changing these settings requires a reload, which is not ideal.
Of course, userstyle.if keeps making complete sense, because CSS can be added and removed without any side-effects. This change would only affect userscripts.

Example addon using this: https://github.com/ScratchAddons/ScratchAddons/blob/master/addons/ctrl-enter-post/addon.json#L32
```json
  "userscripts": [
    {
      "url": "forums.js",
      "matches": [
        "https://scratch.mit.edu/discuss/topic/*",
        "https://scratch.mit.edu/discuss/post/*",
        "https://scratch.mit.edu/discuss/settings/*"
      ],
      "if": {
        "settings": { "forums": true }
      }
    },
    {
      "url": "comments.js",
      "matches": ["https://scratch.mit.edu/studios/*", "https://scratch.mit.edu/users/*", "projects"],
      "if": {
        "settings": { "comments": true }
      }
    }
  ],
```

**Comment by WorldLanguages** [comment]
Affected addons:

- ctrl-enter-post
- exact-count
- infinite-scroll
- my-ocular
- studio-tools

**Comment by DNin01** [comment]
Couldn’t we just make it so that the userscript runs when the setting is enabled? It could increase performance, albeit not by a noticeable amount.

**Comment by CST1229** [comment]
> Couldn’t we just make it so that the userscript runs when the setting is enabled? It could increase performance, albeit not by a noticeable amount.
What about disabling?

**Comment by DNin01** [comment]
> > Couldn’t we just make it so that the userscript runs when the setting is enabled? It could increase performance, albeit not by a noticeable amount.
> 
> 
> 
> What about disabling?
> 
> 

The userscript would still have to handle that. Interrupting JS can cause issues.

**Comment by WorldLanguages** [comment]
> Couldn’t we just make it so that the userscript runs when the setting is enabled? It could increase performance, albeit not by a noticeable amount.

Yes, but it's not really worth it

**Comment by DNin01** [comment]
Dropping this actually does create a difference on the outside:

Addons like `ctrl-enter-post` currently only show up in the Addons tab in the extension popup under "Addons on this tab" if a userscript or userstyle from that addon was injected into the current page, so if you were on a page with a comments section and "enable in comments" was disabled, the addon would not appear under "Addons on this tab".

Without `userscript.if`, `ctrl-enter-post`'s userscripts would always get injected regardless of whether the settings were enabled or not, so it would always appear under "Addons on this tab" on pages with comments sections or forum post composition fields, even if the code in the userscripts was deactivated because of the settings being disabled.

**Comment by WorldLanguages** [comment]
@DNin01 That's a side-effect to consider, but it can be better solved by providing addons with a way to declare themselves as "effectively disabled" even if they're running.

**Comment by DNin01** [comment]
I still don't see how that would be any more convenient than just keeping `if` and making it not require a refresh.

In that case, we would have to add a new addon manifest key to declare that changing settings can dynamically run userscripts, though.

**Comment by DNin01** [comment]
> @DNin01 That's a side-effect to consider, but it can be better solved by providing addons with a way to declare themselves as "effectively disabled" even if they're running.

Actually, this could help with other addons since currently `confirm-actions`, IIRC, is always listed under “Addons on this tab” because its script applies to all pages.
